# vim: ft=python

# Normally I prefer listing every source file so that ninja can pick
# up on added files and regenerate appropriately, but libc has _so_
# many files that it's unweildy. So if a file is added or removed in
# libc, remember to run configure again.

def glob(ext):
    from glob import glob

    def resolve(path):
        from pathlib import Path
        return str(Path(path).relative_to(module_root))

    return list(map(resolve, glob(f"{module_root}/**/*.{ext}", recursive=True)))

sources = []
for ext in ("c", "cpp", "s"):
    sources += glob(ext) + glob(ext + ".cog")

headers = []
for ext in ("h", "inc"):
    headers += glob(ext) + glob(ext + ".cog")

libc = module("libc",
    kind = "lib",
    deps = [ "j6" ],
    sources = sources,
    public_headers = headers,
    )

libc.variables["ccflags"] = [
        "${ccflags}",
        "-DDISABLE_SSE",
        "-DLACKS_UNISTD_H",
        "-DLACKS_FCNTL_H",
        "-DLACKS_SYS_PARAM_H",
        "-DLACKS_SYS_MMAN_H",
        "-DLACKS_SCHED_H",
        "-DLACKS_STRINGS_H",
        "-DHAVE_MMAP=0",
]
