address = 0x6a360000
sections = ["kernel", "sys"]

[[kernel.var]]
name = "version_major"
type = "uint8_t"

[[kernel.var]]
name = "version_minor"
type = "uint8_t"

[[kernel.var]]
name = "version_patch"
type = "uint16_t"

[[kernel.var]]
name = "version_gitsha"
type = "uint32_t"

[[sys.var]]
name = "page_size"
type = "size_t"

[[sys.var]]
name = "large_page_size"
type = "size_t"

[[sys.var]]
name = "huge_page_size"
type = "size_t"

[[sys.var]]
name = "num_cpus"
type = "uint32_t"
