# vim: ft=python

init = module("srv.init",
    targets = [ "init" ],
    deps = [ "libc", "elf", "bootproto", "zstd", "acpi", "pci" ],
    static = True,
    description = "Init server",
    ld_script = "init.ld",
    sources = [
        "device_manager.cpp",
        "initfs.cpp",
        "j6romfs.cpp",
        "loader.cpp",
        "main.cpp",
        "modules.cpp",
        "service_locator.cpp",
        "start.s",
    ])
