# vim: ft=python

boot = module("boot",
    kind = "exe",
    output = "boot.efi",
    targets = [ "boot" ],
    deps = [ "cpu", "elf", "util", "bootproto" ],
    sources = [
        "allocator.cpp",
        "bootconfig.cpp",
        "console.cpp",
        "error.cpp",
        "fs.cpp",
        "hardware.cpp",
        "loader.cpp",
        "main.cpp",
        "memory.cpp",
        "memory_map.cpp",
        "paging.cpp",
        "status.cpp",
        "support.cpp",
        "video.cpp",
    ])

boot.add_depends([
        "main.cpp",
        "memory_map.cpp",
        "paging.cpp",
    ], [
        "${target_dir}/bootproto.dir/include/bootproto/memory.h",
    ])
