# vim: ft=python

module("boot",
    kind = "exe",
    output = "boot.efi",
    targets = [ "boot" ],
    deps = [ "cpu", "elf", "util" ],
    sources = [
        "allocator.cpp",
        "console.cpp",
        "error.cpp",
        "fs.cpp",
        "hardware.cpp",
        "loader.cpp",
        "main.cpp",
        "memory.cpp",
        "memory_map.cpp",
        "paging.cpp",
        "status.cpp",
        "support.cpp",
        "video.cpp",
    ])
