# vim: ft=python

boot = module("boot",
    kind = "exe",
    outfile = "boot.efi",
    targets = [ "boot" ],
    deps = [ "cpu", "elf", "util", "bootproto" ],
    static = True,
    sources = [
        "allocator.cpp",
        "bootconfig.cpp",
        "console.cpp",
        "error.cpp",
        "fs.cpp",
        "hardware.cpp",
        "loader.cpp",
        "main.cpp",
        "memory.cpp",
        "memory_map.cpp",
        "paging.cpp",
        "status.cpp",
        "support.cpp",
        "video.cpp",
    ])
