# vim: ft=python

bp = module("bootproto",
    kind = "lib",
    public_headers = [
        "bootproto/bootconfig.h",
        "bootproto/devices/framebuffer.h",
        "bootproto/init.h",
        "bootproto/kernel.h",
        "bootproto/memory.h.cog",
    ])

from os.path import join

layout = join(source_root, "definitions/memory_layout.yaml")
bp.add_depends("bootproto/memory.h.cog", deps=[layout])
