
def configure(ctx):
    pass

def build(bld):
    sources = bld.path.ant_glob("**/*.cpp")

    bld.stlib(
        source = sources,
        includes = 'include',
        name = 'elf',
        target = 'elf',
        use = 'KUTIL',
    )

# vim: ft=python et
