# vim: ft=python

panic = module("panic.serial",
    kind = "exe",
    output = "panic.serial.elf",
    targets = [ "kernel" ],
    deps = [ "util", "elf", "kernel" ],
    sources = [
        "display.cpp",
        "entry.s",
        "main.cpp",
        "serial.cpp",
        "symbol_table.cpp",
        "../printf/printf.c",
    ])

panic.variables['ldflags'] = ["${ldflags}", "-T", "${source_root}/src/kernel/panic.serial/panic.serial.ld"]
