
def configure(ctx):
    pass

def build(bld):
    sources = bld.path.ant_glob("**/*.cpp")

    bld.program(
        source = sources,
        name = 'makerd',
        target = 'makerd',
        use = 'INITRD KUTIL',
    )

# vim: ft=python et
